### PR TITLE
Update mod links

### LINKED ISSUE #124: Add this new mod to the repository
* Name: More City Locations
* Url: https://github.com/nornagon/cdda-more-city-locations/releases
* Author: nornagon
* Homepage: http://smf.cataclysmdda.com/index.php?topic=14698.msg301740
* Mod not found in version: 1.3.10

(Thanks! :))

### LINKED ISSUE #125: Add this new mod to the repository: Chaosvolt's Arcana (not built in)
* Name: Arcana
* Url: https://github.com/chaosvolt/cdda-arcana-mod
* Author: chaosvolt
* Homepage: http://smf.cataclysmdda.com/index.php?topic=10987.0
* Mod not found in version: 1.3.10

Game's built in Arcana is currently deprecated with low if any chance of coming back (I do not disagree with the reasons for banning Chaosvolt). I love the idea of the more "otherworldly" things happening in Cataclysm (we have shoggoths after all).
Currently I am using a shell script to auto update Arcana from the above repo. It would be nice to have (up to date) Arcana added to the launcher.
Here is my update script if you are interested:
```
@echo off
rd /s /q backup\Arcana\
move c:\Games\Cataclysm\data\mods\Arcana backup
cd cdda-arcana-mod\
git pull
dir
xcopy Arcana c:\Games\Cataclysm\data\mods\Arcana\
cd ..
```

### LINKED ISSUE #131: Add `dda-lua` mods to launcher
Forum page: http://smf.cataclysmdda.com/index.php?topic=14861.0
Repository: https://github.com/ZhilkinSerg/Cataclysm-DDA-LUA
Releases: https://github.com/ZhilkinSerg/Cataclysm-DDA-LUA/releases

### LINKED ISSUE #142: Add new mod: No Makeshift Guns Mod
Just an exclusion mod

- Name: No Makeshift Firearms

- URL: https://github.com/Cyrano7/No-Makeshift-Firearms-Mod

- Author: Cyrano7

- Homepage: https://discourse.cataclysmdda.org/t/no-makeshift-guns-mod

Thank you! Would it be better to submit a PR instead?

### LINKED ISSUE #143: Please, add this new mod to the repository?
* Name: Craft Ammo Magazines & Belt Links
* Url: https://drive.google.com/open?id=1yUoz9XrSGG7TaLpWzNMCFKMS-2lETuuU
** Extension URL: https://drive.google.com/open?id=1rfZUhaJAGMOKIWzfdN7wuJnJH6bGBZAl
* Author: ShadowDragon8685 (That's me)
* Homepage: https://discourse.cataclysmdda.org/t/craftable-ammunition-magazines/14607
* Mod not found in version: 1.3.10

I made a couple of mods for CDDA. The first one and its extension, which extends the Real Guns mod, simply allows the player to craft factory-specification ammunition magazines.

### LINKED ISSUE #144: Also please add this new mod to the repository
* Name: Wintertime Classes
* Url: https://drive.google.com/open?id=1Syut09Asr393JYkzND3-FAYcR5sv_jFM
* Author: ShadowDragon8685
* Homepage: https://discourse.cataclysmdda.org/t/wintertime-classes/14608
* Mod not found in version: 1.3.10

The other mod I made adds new classes to the game; all are geared to presume a cold-weather start, and most are simply practically clones of existing stock classes.

### LINKED ISSUE #145: Add this new mod to the repository
* Name: Storage Battery Conversions
* Url: https://drive.google.com/open?id=1cEN6MG--udSFDIf03Yulazp049oSvQZ_
* Author: ShadowDragon8685
* Homepage: https://discourse.cataclysmdda.org/t/battery-conversion-brightnights-to-vanilla/14639
Simple, almost trivial QoL mod I made primarily to satisfy my own needs, but which others may find useful, allowing the end-user to convert BrightNights' batteries to vanilla storage batteries and vice-versa.

### LINKED ISSUE #154: Add this new mod to the repository please
* Name: Oa's additional buildings mod
* Url: https://github.com/Narroe/oa_additional_buildings_mod/archive/master.zip
* Author: Oa
* Homepage: https://github.com/Narroe/oa_additional_buildings_mod
* Mod not found in version: 1.3.10

a mod that adds more buildings to the city and the wilderness around it.

### LINKED ISSUE #160: Incorrect Mod Link
The download URL for the Cataclysm++ mod is wrong (missing a character), here is the correct one

https://github.com/Noctifer-de-Mortem/nocts_cata_mod/archive/master.zip

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
# What was changed:

- links were updated to used new forum (http://discourse.cataclysmdda.org/);
- fixes #160;
- fixes #154;
- fixes #145;
- fixes #144;
- fixes #143;
- fixes #142;
- fixes #131;
- fixes #125;
- fixes #124;

### CODE REVIEW

**Comment by remyroy** [comment]
Thanks for your work. I'll review these changes shortly.

You should avoid modifying the version number in a pull request. It will be done just before a release.

**Comment by ZhilkinSerg** [comment]
> You should avoid modifying the version number in a pull request. It will be done just before a release.

Yes, version change should not be here. That was a local test commit.

**Comment by remyroy** [comment]
The dda-lua-* mods all have the same url. Is this a mistake or is this correct? If they all have the same download url, they should just be a single entry in the repository.

**Comment by remyroy** [comment]
Whaleys Small Town Building Pack's download url doesn't work anymore. The entry should probably be removed until the author or someone fixes this.

**Comment by remyroy** [comment]
I think the download URL for Whaleys Small Town Building Packs should be 
https://www.dropbox.com/s/1rtpemg9pxbt0lb/Small%20Town%20Building%20Pack.zip?dl=1

**Comment by ZhilkinSerg** [comment]
>I think the download URL for Whaleys Small Town Building Packs should be
https://www.dropbox.com/s/1rtpemg9pxbt0lb/Small%20Town%20Building%20Pack.zip?dl=1

Yes, thanks.

> The dda-lua-* mods all have the same url. Is this a mistake or is this correct? If they all have the same download url, they should just be a single entry in the repository.

`dda-lua-*` is collection of multiple mods which come in same archive (https://github.com/ZhilkinSerg/Cataclysm-DDA-LUA/archive/master.zip). It would be good if launcher supported downloading and caching of single archive and unpacking multiple mods from this archive.

**Comment by remyroy** [comment]
I can implement installing multiple distinct mods from a single archive. This will require a new format for the mods.json repository data as I check for existing mods with the same ident value and I expect a single value with the ident property in that JSON file.

So instead of many entries with `"ident": "something"`, you should have a single entry with:

`"ident": ["dda-lua", "dda-lua-fun", "dda-lua-items", "dda-lua-skills", "dda-lua-traits"]`

**Comment by remyroy** [comment]
Implementation for installing archives containing multiple mods has been added with b9da9cecfd5bfdcf81ce42f379ec8f4bca18a5cf and 6518d716256d86166f57d7cf040ac4604dc7f308. If you want to include your mods with a single entry in mods.json like I mentionned, I'll merge this pull request.

**Comment by ZhilkinSerg** [comment]
> Implementation for installing archives containing multiple mods has been added with b9da9ce and 6518d71. If you want to include your mods with a single entry in mods.json like I mentionned, I'll merge this pull request.

Thanks. Done.

**Pull request merged**
