### PR TITLE
Add a link to recently merged PRs

### PR DESCRIPTION
**Pull request by Inglonias**
I thought it might be helpful to throw people running the experimentals a bone, and add a link to recently closed PRs. Just an idea.

### CODE REVIEW

**Comment by Zireael07** [comment]
'closed' or 'merged'? which do you mean?

**Comment by Inglonias** [comment]
> 
> 
> 'closed' or 'merged'? which do you mean?

In this context, a "merged" PR was added to the master branch and represents something that you can expect to see in-game. A "closed" PR is a PR that was not added to the master branch for whatever reason, either because the author changed their mind or Kevin said no.

**Comment by Zireael07** [comment]
Exactly, so why show the closed PRs? I'd show the most recently merged - let's say five, so people know where their experimental sits in the PR queue, but closed PRs don't really matter since they weren't added.

**Comment by Inglonias** [comment]
Didn't realize I could replaced "is:closed" with "is:merged". I'll go do that.

**Comment by Inglonias** [comment]
this repo is no longer being maintained so this won't ever get merged. Oh well. If you want a launcher with a changelog, use Catapult.

**Pull request closed without merging**
