### PR TITLE
Updated russian translation

### PR DESCRIPTION
**Pull request by Night-Pryanik**

### CODE REVIEW

**Comment by remyroy** [comment]
@devilstars What do you think of these changes?

**Comment by devilstars** [comment]
It's ok. Some typos fixed and missing commas added.

**Comment by remyroy** [comment]
Thanks for the typos fixes. I'm merging those changes. @Night-Pryanik Would you like to be included in the thanks section for translators? If so, what name and/or link would you like me to put for you?

**Comment by Night-Pryanik** [comment]
@remyroy Well, why not? Night_Pryanik (with underline) will do.

**Pull request merged**
