### PR TITLE
Add support for mac os

### PR DESCRIPTION
**Pull request by Veid**
I used the changes from this https://github.com/remyroy/CDDA-Game-Launcher/pull/80 and added some fixes. Looks like it works

### CODE REVIEW

**Comment by remyroy** [comment]
Good stuff. Give me some time to review this and I'll come back to you.

**Comment by Leland** [comment]
Would love to see this merged

**Comment by prateek** [comment]
+1 for this, I've been able to use Veid's version on my MBP just fine. 

Only comment would be to point out people need to run `pip install -r posix.txt` somewhere in the README/BUILD texts.

**Comment by BeardedMenace** [comment]
Are there any plans to eventually merge this in?

**Comment by remyroy** [comment]
There is no plan to add and support a MacOS version at this time.

**Pull request closed without merging**
