### PR TITLE
Add infrastructure to create an InnoSetup installer for CDDAGL

### PR DESCRIPTION
**Pull request by KurzedMetal**
So, with this PR you can now create an installer for the PyInstaller multi-file compiled stuff in `dist\launcher` by simply running `python setup.py innosetup`.

Most of changes in the PR:
* I made `python setup.py installer` create the "multi-file" build instead of the single-file build by default, which is the better PyInstaller compilation method now that we can create an InnoSetup Installer, as this change will speed up start up time.
* I created a VERSION file in the root of the project, it's used by Inno and setup.py after this PR, the idea is to have a centralized (single) place to change the version and not having to manually edit multiple locations. I know `cddagl\__version__.py` has the version too, but I didn't want to `open()` VERSION from there to read the value, I'll leave it to your decision if you wanna do that.
* Created `launcher.iss` which gives the directives on how to build the installer, it has custom Pascal code to make sure it always uninstall previous version before installing the new one. I know you wanted version check, but IMO it's not needed or wanted. The good think about not having version check is that will let the player upgrade AND downgrade in case you fkup some release :P The most important thing is that they can just download an installer and spam Next and have CDDAGL installed correctly.
* Like I mentioned in the first sentence: I added a `setup.py` command for easy building and consistent building of the Installer. `launcher.iss` has a lot of relatives paths to the base directory of the project and this custom command makes sure it always runs from it to avoid errors. If you have Inno Setup installed in the stantard place `python setup.py innosetup` is enough, if not, `python setup.py innosetup --compiler=path/to/inno/compil32.exe` should work too.
* Seems like Inno don't handle well UTF8 text files if they don't have UTF8 BOM, so I added it to LICENSE and `launcher.iss`, make sure you don't delete those by mistake as you can't see them (any modern editors should work).

Other than that, I made a lot of testing and seems to work great, the only testing I didn't do was to use a "clean" windows install (aka new Windows virtual machines) to check what happens when the user never had CDDAGL installed before (I obviously installed uninstalled in my PC dozens of time but I also had it configured an running even before doing this PR).

I'm also assuming CDDAGL don't require write permissions to the installation folder (I hope you are using other places to save settings and the initial/default installation folder is not where the launcher executable is). If this is not the case, it will probably require some extra changes to cope with the fact that from now installation directory / launcher executable directory should never be used for other than reading installed stuff.

Example of a built installer with the latest code and this PR, just in case someone wanna try it without compiling them themselves: https://www.dropbox.com/s/s6xtwtmzzo75t19/cddagl_installer_v1.3.22.exe?dl=1

Thoughts about the Auto-Update process:
AFAIK It's currently broken (?). But since you can build an installer now, it should be easy to re-implement it by checking if there's any new version, point to the user to a HTTP link with the latest version installer for download and let the user spam "Next" and the installer will kill the launcher if running, uninstall the previous version and install the new one for a smooth and simple update.

### CODE REVIEW

**Comment by KurzedMetal** [comment]
This should fix the slowness reported in #283

**Comment by remyroy** [comment]
The launcher doesn't need write permission in its folder but it needs read permission for a few files. That seems to work. It writes what it needs in `%LOCALAPPDATA%\CDDA Game Launcher`.

I did a few tests as well and everything seems to work well. However, I think a few minor points should be changed.

- You need to call 2 commands to build with PyInstaller (`python setup.py installer`) and create the setup with Inno Setup (`python setup.py innosetup`). It would be nice to have a single command that would perform all of this. If we want to keep those existing commands, it might be a good idea to rename them so they don't get confusing in the future. The current installer command could be renamed to freeze, the current innosetup could maybe keep its name and a new command could be named fullinstaller or something else just so we know what everything does without too much confusion.
- Since `VERSION` is now the new source for the version number, I think we should generate the `cddagl\__version__.py` file from that source. We could maybe have the installer command overwrite `cddagl\__version__.py` with the value in `VERSION` before starting the PyInstaller stuff. In `cddagl\launcher.py`, we could always overwrite `cddagl\__version__.py` with the value in `VERSION` when we are not in a bundle (frozen with PyInstaller). With these 2 changes, we could even exclude `cddagl\__version__.py` from the git repository to avoid any more confusion about the source of the version number.

With these changes, I'll be able to remove the update batch script, exclude it from the bundle and rework the launcher auto-updater to simply launch the setup.

**Comment by KurzedMetal** [comment]
Yeah, I was thinking about doing a single command, but I left it out because it wasn't super important. But I got you :)

As for reading version inside the module: I was hesitant to `open()` the `VERSION` from the package because the file wasn't inside the package, but I think this `VERSION` file does belong inside the package... Since it's the version package anyways. And that's what I did, I moved `VERSION` inside the 'cddagl' package, made every reference use that path instead and included it as package data in both python distributions and pyinstaller freeze (and obviously the InnoSetup Installer)

So I think you finally got what you wanted: single command to build the installer, new names for the commands (I was actually thinking that changing "installer" was a good idea), a single place that needs to be edited for the Version number.

**Comment by remyroy** [comment]
Excellent work as usual! Merging.

**Comment by remyroy** [comment]
I want to fix a few remaining issues before the next release but I think this deserve a bump to 1.4 for the next one.

**Comment by KurzedMetal** [comment]
Cool, if any bugs popup or you need any help related to this, just tag me and I'll see what I can do :)

**Pull request merged**
