### PR TITLE
Deny players updating if they install CDDAGL inside CDDA folder

### LINKED ISSUE #350: Launcher missing files
after you update the game the launcher deletes itself
Untitled

### PR DESCRIPTION
**Pull request by KurzedMetal**
Improve checks on user selected game directory.
Add a cute icon hinting the state of the directory.
This fixes #350, when the user install CDDAGL inside CDDA, they'll get an error inside the launcher, won't be able to update, install or do anything unless they change either CDDAGL installation or CDDA folder.

### CODE REVIEW

**Comment by KurzedMetal** [comment]
Ok, I just noticed a few more parts of the code directly handle the Enabled state of that button directly.
I'll have to check every of those lines goes through the new validations.
This is why separating UI logic from model is a good idea (I've been trying to do it on some tabs, It's quite hard to achieve, it's all too entangled right now, I'm hoping small changes will improve the situation in a long run).

Don't merge yet, until I tell you, it's definitely not finished yet.

**Comment by KurzedMetal** [comment]
I was hunting for direct calls to `update_button.setEnabled()` and there was a reference to that in `enable_controls`, which was used in multiple parts of the application... but fortunately none of the calls to it was setting the `update_button` param to True (which was the part I was worried about). I removed that param because anything calling that would be skipping the old and new checks in `game_directory_changed()`. After that change, `disable_buttons` and `enable_buttons` will only handle "previous state" only, which is fine.

Also removed a lonely `update_button.setEnabled(True)` and a `self.previous_ub_enabled = True` that was executed after refreshing the build list. I haven't found a reason why these lines where there, but those would interfere with the validated start of the button set in `game_directory_changed()`.

So, from now on, the enable of the `update_button` should only be set enabled from `game_directory_changed()`, `disable_buttons` can disable as it please, and `enable_buttons` can only enable if it was previously enabled by `game_directory_changed()`.

@remyroy can you check if this may be breaking any logic? I did some manual local tests and they seem fine but I could be missing something.

**Comment by KurzedMetal** [comment]
I **think** that using `Use launcher directory as the game directory` was potentially corrupting the player saves too because it was using exactly the same directory and not a subdirectory.

I changed it to install the game in a subdirectroy inside CDDAGL, like `{cddagl_path}\cdda\`.

**Comment by remyroy** [comment]
I think the *Use launcher directory as the game directory* option should be removed.

**Comment by KurzedMetal** [comment]
Any particular reason why you want to remove it?

I think it's simple enough to keep it around. I do see an use case for players that use CDDAGL in pendrives or could sync services like dropbox, because the option makes CDDAGL pick the correct directory on start without having to change it manually on the different PCs even if they are located in different directories.

The only think that this option could break is when CDDAGL is installed in `Program Files` and and the user executing it don't have write access. I guess I could even include a check for that in the `game_directory_changed()` to invalidate the directory if it doesn't have write access.

**Comment by remyroy** [comment]
I was thinking about removing the option because it can cause confusion and because of the complexity but I can see your point about the usefulness. 

I have not had time to check the code yet. I've been away and quite busy these past few days. I'll try to review #362 first today.

**Comment by remyroy** [comment]
On a portable/cloud sync/usb stick use case, it might be easier to suggest users to install the launcher along side in a different folder. For exemple:

root
| -- cdda folder
| -- launcher folder

**Comment by KurzedMetal** [comment]
But then, when the player uses the launcher in a PC where the USB is assigned to `G:`, he will have to change the path in CDDAGL, and when he moves to another PC and the SO assigns another letter he will not get the correct directory loaded on launcher. With this option, the launcher currently opens the correct directory without any change, as the Launcher calculate the game directory each time it gets launched.

Same happens if the user use something like Dropbox for sync, and one PC has the files in `C:\Dropbox\games\cdda_launcher` and in another PC it's on `D:\Documents\Dropbox\cdda_launcher`.

Like I said before, I'm not that interested in this option, if you want to remove it, fine by me. I just tried to fix it a little bit because before that commit it was corrupting data on a similar fashion as what the PR was trying to fix (which is users manually installing CDDAGL inside CDDA).

**Comment by remyroy** [comment]
Keeping the option is a pain but I think I see your point and the use cases for it. We'll keep it.

**Comment by remyroy** [comment]
Sorry for the long delay on reviewing this PR.

The `Saves:` textbox stays at 'Analyzing...' if there are no saves. 

analyzing

I would prefer the issue indicator to be located on the right and only show if there is an actually issue. Something similar the when your saves directory size is somewhat large.

large-saves

**Comment by KurzedMetal** [comment]
The "Analyzing..." when is empty was I bug, I fixed it.

As for the warning indicator you mention, I didn't add any new warning for the saves (I did add a few for the directory, but it has an icon already) and checking the code I already see one in place for the save size like you mention.

**Comment by remyroy** [comment]
I meant the directory issue indicator. I think it should only be shown when there is an actual issue and on the right side.

**Comment by KurzedMetal** [comment]
Oh... Right or left of the `...` button?

**Comment by remyroy** [comment]
Right of the ... button would be better I think.

**Comment by remyroy** [comment]
There seem to be some conflicting changes with the master branch. Can you resolve them?

**Comment by KurzedMetal** [comment]
Done! Sorry I didn't notice the conflict before.

**Comment by remyroy** [comment]
Again, sorry for the delay. Seems good. Merging.

**Pull request merged**
