### PR TITLE
Refactor: removing some dependencies and globals

### PR DESCRIPTION
**Pull request by KurzedMetal**
Read the commit messages, they provide more than enough info. I'd rather not repeat myself :P
Anyways, if anything is not clear, just ask.

### CODE REVIEW

**Comment by remyroy** [comment]
Let me know when you will be done with this one. I would like to avoid merging something halfway done.

**Comment by KurzedMetal** [comment]
I try to make small changes in each commit leaving the app in a consistent/buildable state each time.
If I push something, you are good to review it and merge it whenever you want.

I just keep adding more commits to this PR because I feel the changes are related and the PR is still open, but I wouldn't mind open a new one. Actually, merging as soon as you review it would be better to avoid conflicts.

Anyways, the worst thing can happen is that I need to open another PR to add more refactor I'm working on and nothing more.

BTW, I'm currently working in more refactors to launcher.py and the sqlalchemy stuff, I'll probably push soon. I'm trying to remove as much as logic and variables from globals as I can before I start moving stuff to new files. I'm trying to do small code transformations that I know won't break anything before doing any more risky changes.

**Comment by KurzedMetal** [comment]
I'm getting the feel we are in a situation where you don't merging because you are waiting for more pushs and I don't want to push because I don't want to have multiple PRs (merge conflicts) or a mega-PR opened :P
But here I go with the Mega-PR, since my changes already depends on the ones in this PR, I can't open a new one.

**Comment by KurzedMetal** [comment]
I removed / lowered most of the global dependencies that would've caused problems when splitting ui.py classes to another files. I think it's ready to start splitting `ui.py` classes into different files.

**Comment by KurzedMetal** [comment]
Done, moved **everything** out of ui.py into different files.
It actually doesn't exist anymore.

**Comment by remyroy** [comment]
I cannot start the launcher using `python cddagl\launcher.py` from the project directory. I get the following error:

```
Traceback (most recent call last):
  File "cddagl\launcher.py", line 13, in <module>
    import cddagl.constants as cons
ModuleNotFoundError: No module named 'cddagl'
```

It is the reason why I initially added the projet path in sys.path in launcher.py with:

```python
if getattr(sys, 'frozen', False):
    # we are running in a bundle
    basedir = sys._MEIPASS
else:
    # we are running in a normal Python environment
    basedir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    sys.path.append(basedir)
```

before importing anything from cddagl. There might be a better way of doing this but it would be nice for this to work.

**Comment by KurzedMetal** [comment]
Yes, my bad, my IDE (PyCharm) is automatically adding the project dir to PYTHONPATH, so I didn't needed sys.path mangling.

**Comment by remyroy** [comment]
I'm not sure the sys.path manipulation is needed for when the launcher is bundled or frozen with pyinstaller. Let me double check that.

**Comment by KurzedMetal** [comment]
It wouldn't make much difference, there's no need to check if it is frozen to modify sys.path.

**Comment by remyroy** [comment]
It's not about the ability to modify sys.path, but it's more about being correct and avoiding potentially breaking paths in there.

I just did the test with a frozen bundle. The path in __file__ is the executable. So adding the parent directory to the executable is wrong and potentially dangerous. For instance, if the bundle is installed with the installer in the same directory with many other programs (`%LOCALAPPDATA%\Programs` for instance which is the default path for the InnoSetup installer), Python is potentially going to be looking for packages or modules in other programs directories.

We should only add that path if we are not in a frozen bundle.

**Comment by KurzedMetal** [comment]
BTW, the PR branch is set as "Allow edits from maintainers", you should be able to make changes to PR yourself if want. I wouldn't mind.

**Comment by remyroy** [comment]
Good to know.

**Comment by KurzedMetal** [comment]
Another way to avoid that import error without editting sys.path is:
* Obviously, devs modifying PYTHONPATH correctly
* If configured correctly, `python -m cddagl` (just pushed)
* Creating a `run.py` script at the root of the repository with a content:
```
import cddagl.launcher
cddagl.launcher.run_cddagl()
```
and running that instead of `launcher.py` when developing.
This works because python adds the script file to sys.path automatically, but since the project is curently running `launcher.py` directly it adds the `project_folder\cddagl\` instead of `project_folder\`

**Comment by remyroy** [comment]
Seems good. Merging.

**Pull request merged**
