### PR TITLE
Add machine-readable license and copyright metadata

### PR DESCRIPTION
**Pull request by hexagonrecursion**
* Licensing and copyright are important to some people (e.g. me).
* Whenever practical metadata should be machine-readable.
* For source code repositories the [REUSE Specification](https://reuse.software/spec/) is a standard license and copyright metadata format.

Congratulations! Your project is compliant with version 3.0 of the REUSE Specification :-)

### CODE REVIEW

**Comment by hexagonrecursion** [comment]
Note: the PR includes a github action to validate REUSE compliance in CI. If this needs more discussion, I can remove the file form this PR and submit it separately.

**Comment by hexagonrecursion** [comment]
ping @remyroy

**Comment by remyroy** [comment]
This project is now unmaintained.

**Comment by hexagonrecursion** [comment]
You should **not** feel bad about this: you have given us a **great** tool and maintained it **since 2015**. You are **awesome**!

If I were you I would post on <https://www.reddit.com/r/cataclysmdda> saying "I have stopped maintaining the launcher. Feel free to fork and continue where I left off"

**Comment by hexagonrecursion** [comment]
Resubmitted as https://github.com/DazedNConfused-/CDDA-Game-Launcher/pull/36

**Pull request closed without merging**
